export const dummySkills: SkillRecord[] = [
	{
		id: "sk_001",
		title: "Write Code",
		slug: "write-code",
		description:
			"Generate clean, production-ready TypeScript and React code from prompts.",
		category: "Development",
		tags: ["coding", "typescript", "react"],
		installCommand: "npx agent-skills install write-code",
		createdAt: "2026-04-18T10:00:00.000Z",
		authorClerkId: "user_abc123",
		authorEmail: "alice@example.com",
	},
	{
		id: "sk_002",
		title: "Debug Errors",
		slug: "debug-errors",
		description:
			"Analyze stack traces and suggest precise fixes for runtime and build issues.",
		category: "Development",
		tags: ["debugging", "errors", "logs"],
		installCommand: "npx agent-skills install debug-errors",
		createdAt: "2026-04-18T10:05:00.000Z",
		authorClerkId: "user_def456",
		authorEmail: "bob@example.com",
	},
	{
		id: "sk_003",
		title: "Optimize Prompt",
		slug: "optimize-prompt",
		description:
			"Rewrite prompts for clarity, structure, and better LLM output quality.",
		category: "Prompt Engineering",
		tags: ["prompting", "llm", "optimization"],
		installCommand: "npx agent-skills install optimize-prompt",
		createdAt: "2026-04-18T10:10:00.000Z",
		authorClerkId: "user_ghi789",
		authorEmail: "carol@example.com",
	},
	{
		id: "sk_004",
		title: "Generate Tests",
		slug: "generate-tests",
		description:
			"Create unit and integration tests for components, hooks, and API routes.",
		category: "Testing",
		tags: ["testing", "jest", "vitest"],
		installCommand: "npx agent-skills install generate-tests",
		createdAt: "2026-04-18T10:15:00.000Z",
		authorClerkId: "user_jkl012",
		authorEmail: "dave@example.com",
	},
	{
		id: "sk_005",
		title: "Create Docs",
		slug: "create-docs",
		description:
			"Produce README sections, API docs, and setup guides from source code.",
		category: "Documentation",
		tags: ["docs", "readme", "api"],
		installCommand: "npx agent-skills install create-docs",
		createdAt: "2026-04-18T10:20:00.000Z",
		authorClerkId: "user_mno345",
		authorEmail: "eve@example.com",
	},
	{
		id: "sk_006",
		title: "Review Pull Request",
		slug: "review-pull-request",
		description:
			"Review PR changes for bugs, regressions, and code quality improvements.",
		category: "Code Review",
		tags: ["review", "pull-request", "quality"],
		installCommand: "npx agent-skills install review-pull-request",
		createdAt: "2026-04-18T10:25:00.000Z",
		authorClerkId: "user_pqr678",
		authorEmail: "frank@example.com",
	},
];
